# edushiwei-service Global Configuration

# jwt configuration
jwt:
  signing-key: 'eduShiwei'
  expires-time: 604800
  buffer-time: 86400

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[EDU-SHIWEI]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: '192.168.229.129:6379'
  password: '111111'

# email configuration
email:
  to: 'xxx@qq.com'
  port: 465
  from: 'xxx@163.com'
  host: 'smtp.163.com'
  is-ssl: true
  secret: 'xxx'
  nickname: 'test'

# system configuration
system:
  env: 'public'  # Change to "develop" to skip authentication for development mode
  addr: 8080
  db-type: 'mysql'
  oss-type: 'local'    # 控制oss选择走本期还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-multipoint: false

# mysql connect configuration
mysql:
  path: '192.168.229.129:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'edushiwei'
  username: 'root'
  password: '111111'
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""

  # local configuration
local:
  path: 'uploads/file'